return {
  { "sbdchd/neoformat" },
  { "itchyny/lightline.vim" },
  { "scrooloose/nerdcommenter" },
  { "michaeljsmith/vim-indent-object" },
  { "tpope/vim-fugitive" },
  { "windwp/nvim-autopairs" },
  { "souffle-lang/souffle.vim" },
  { "dense-analysis/ale" },
  { "github/copilot.vim" },
  { "neoclide/coc.nvim", branch = "release" },
  { "Julian/lean.nvim" },
  { "neovim/nvim-lspconfig" },
  { "nvim-lua/plenary.nvim" },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  { "MunifTanjim/nui.nvim" },
  { "MeanderingProgrammer/render-markdown.nvim" },
  { "hrsh7th/nvim-cmp" },
  { "nvim-tree/nvim-web-devicons" },
  { "HakonHarnes/img-clip.nvim" },
  { "zbirenbaum/copilot.lua" },
  { "stevearc/dressing.nvim" },
  { "folke/snacks.nvim" },
  { "yetone/avante.nvim", branch = "main", build = "make" },
  { "olimorris/codecompanion.nvim", version = "^18.0.0", opts = {},
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
  },
}
