return {
  { "sbdchd/neoformat" },
  { "itchyny/lightline.vim" },
  { "scrooloose/nerdcommenter" },
  { "michaeljsmith/vim-indent-object" },
  { "tpope/vim-fugitive" },
  { "KihongHeo/vim-dafny" },
  { "windwp/nvim-autopairs", event = "InsertEnter", config = true },
  { "souffle-lang/souffle.vim" },
  { "dense-analysis/ale" },
  { "github/copilot.vim" },
  { "neoclide/coc.nvim", branch = "release" },
  { "neovim/nvim-lspconfig" },
  { "nvim-lua/plenary.nvim" },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      ensure_installed = { "html", "css", "markdown", "markdown_inline" },
      highlight = { enable = true },
    },
  },
  { "nvim-tree/nvim-web-devicons" },
  { "HakonHarnes/img-clip.nvim" },
  { "zbirenbaum/copilot.lua" },
  { "stevearc/dressing.nvim" },
  { "folke/snacks.nvim" },
}
